spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.maite.shuadanmonitor.shuadantool: debug # 开启数据库执行语句打印在控制台
#  config: classpath:logback-spring.xml #springboot 默认指定
